### ISSUE TITLE
OS X Only?

### ISSUE THREAD

**Issue by kihashi** [drheld/pianoctl#1]
I forked this to try to use it for a project that I am working on, but as I was trying to get it set up on my linux computer, I ran into a problem installing dependencies: appscript is an applescript bridge and therefore only builds on OS X.

Could you mark somewhere in the repo that the code only works on OS X? Might save someone else some trouble.

Thanks!

**Comment by drheld** [comment]
I think the only OS X specific part of the code is for volume control? This could probably be changed over to control the volume through pianobar instead to work better. Would that take care of your problem?
